name: smarttools
description: SmartTools ID
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  image_picker: ^1.0.7
  image: ^4.1.7
  path_provider: ^2.1.2
  http: ^1.2.0
  video_player: ^2.7.2

flutter:
  uses-material-design: true
