name: smarttools
description: Smart Tools App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.0.17
  path_provider: ^2.0.15
  http: ^1.1.0
  google_mobile_ads: ^5.0.0

flutter:
  uses-material-design: true
